# Generated by Django 6.0.1 on 2026-01-16 17:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100, verbose_name='Route Name')),
                ('route_number', models.CharField(max_length=20, verbose_name='Route Number')),
                ('start_point', models.CharField(max_length=100, verbose_name='Start Point')),
                ('end_point', models.CharField(max_length=100, verbose_name='End Point')),
                ('departure_time', models.TimeField(verbose_name='Departure Time')),
                ('arrival_time', models.TimeField(verbose_name='Arrival Time')),
                ('via', models.TextField(blank=True, verbose_name='Via (Stops)')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Image')),
                ('location_url', models.URLField(blank=True, verbose_name='Location Map URL')),
            ],
        ),
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('AUTO', 'Auto Rickshaw'), ('TEMPO', 'Tempo'), ('OTHER', 'Other')], max_length=20, verbose_name='Service Type')),
                ('provider_name', models.CharField(max_length=100, verbose_name='Provider/Driver Name')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='Contact Number')),
                ('stand_location', models.CharField(max_length=100, verbose_name='Stand Location')),
                ('service_area', models.TextField(verbose_name='Service Area')),
            ],
        ),
    ]
