# Generated by Django 6.0.1 on 2026-01-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route_name',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='route_number',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(default='', max_length=100, verbose_name='Bus Name'),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(default='', max_length=20, verbose_name='Bus Number'),
        ),
    ]
