# Generated by Django 6.0.1 on 2026-01-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_bus_route_name_remove_bus_route_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Location Map URL'),
        ),
    ]
