# Generated by Django 6.0.1 on 2026-01-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_place_location_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='bus',
            name='time',
            field=models.TimeField(default='00:00:00', verbose_name='Time'),
        ),
    ]
