# Generated by Django 6.0.1 on 2026-02-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportservice',
            name='service_type',
            field=models.CharField(choices=[('AUTO', 'Auto Rickshaw'), ('TEMPO', 'Tempo'), ('OTHER', 'Car/Taxis')], max_length=20, verbose_name='Service Type'),
        ),
    ]
