# Generated by Django 6.0.1 on 2026-02-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_alter_transportservice_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportservice',
            name='service_area',
            field=models.TextField(blank=True, null=True, verbose_name='Service Area'),
        ),
        migrations.AlterField(
            model_name='transportservice',
            name='stand_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stand Location'),
        ),
    ]
